export const ADD_NEW_NOTICE = 'ADD_NEW_NOTICE';

export const DIRECTORIES_FETCH_STARTED = 'DIRECTORIES_FETCH_STARTED';
export const DIRECTORIES_FETCH_SUCCEED = 'DIRECTORIES_FETCH_SUCCEED';
export const DIRECTORIES_FETCH_FAILED = 'DIRECTORIES_FETCH_FAILED';

export const NOTICES_FETCH_STARTED = 'NOTICES_FETCH_STARTED';
export const NOTICES_FETCH_SUCCEED = 'NOTICES_FETCH_SUCCEED';
export const NOTICES_FETCH_FAILED = 'NOTICES_FETCH_FAILED';

export const ADD_NEW_DIRECTORY_STARTED = 'ADD_NEW_DIRECTORY_STARTED';
export const ADD_NEW_DIRECTORY_SUCCEED = 'ADD_NEW_DIRECTORY_SUCCEED';
export const ADD_NEW_DIRECTORY_FAILED = 'ADD_NEW_DIRECTORY_FAILED';

export const ADD_NEW_NOTICE_STARTED = 'ADD_NEW_NOTICE_STARTED';
export const ADD_NEW_NOTICE_SUCCEED = 'ADD_NEW_NOTICE_SUCCEED';
export const ADD_NEW_NOTICE_FAILED = 'ADD_NEW_NOTICE_FAILED';

export const DELETE_DIRECTORY_STARTED = 'DELETE_DIRECTORY_STARTED';
export const DELETE_DIRECTORY_SUCCEED = 'DELETE_DIRECTORY_SUCCEED';
export const DELETE_DIRECTORY_FAILED = 'DELETE_DIRECTORY_FAILED';

export const DELETE_NOTICE_STARTED = 'DELETE_NOTICE_STARTED';
export const DELETE_NOTICE_SUCCEED = 'DELETE_NOTICE_SUCCEED';
export const DELETE_NOTICE_FAILED = 'DELETE_NOTICE_FAILED';
