export const ADD_NEW_DIRECTORY = 'ADD_NEW_DIRECTORY';
export const ADD_NEW_NOTICE = 'ADD_NEW_NOTICE';

export const DIRECTORIES_FETCH_STARTED = 'DIRECTORIES_FETCH_STARTED';
export const DIRECTORIES_FETCH_SUCCEED = 'DIRECTORIES_FETCH_SUCCEED';
export const DIRECTORIES_FETCH_FAILED = 'DIRECTORIES_FETCH_FAILED';

export const NOTICES_FETCH_STARTED = 'NOTICES_FETCH_STARTED';
export const NOTICES_FETCH_SUCCEED = 'NOTICES_FETCH_SUCCEED';
export const NOTICES_FETCH_FAILED = 'NOTICES_FETCH_FAILED';

export const ADD_NEW_DIRECTORY_STARTED = 'DIRECTORIES_FETCH_STARTED';
export const ADD_NEW_DIRECTORY_SUCCEED = 'DIRECTORIES_FETCH_SUCCEED';
export const ADD_NEW_DIRECTORY_FAILED = 'DIRECTORIES_FETCH_FAILED';
